### ISSUE TITLE
API unclear.  How to apply scrollbar to flex column layout?

### ISSUE THREAD

**Issue by boxofrox** [PPakalns/egui_taffy#5]
I see provisions for `scroll_width`, `scroll_height`, and `scrollbar_size` in `Layout` and `scrollbar_width` and `Overflow::Scroll` in `CoreStyle`.

What I fail to understand is how to use these pieces to create a flex column that scrolls when the content height exceeds the column height.  Applying `scrollbar_width` and `overflow = Overflow::Scroll` to the flex column style has no effect.  All content is drawn, even beyond the bounds of the flex column; no scrollbar appears; mouse scroll wheel has zero effect.

Should I use an egui scroll area with the flex column inside to create a scrolling flex column?

If so, what purpose do the provisions I mention serve in that regard?

**Comment by PPakalns** [comment]
This is area that egui_taffy is looking into supporting.

---

Currently taffy supports adding overflow style setting ( https://pop-os.github.io/libcosmic/taffy/style/enum.Overflow.html )  to layout element to signify how content will overflow and if scrollbar must be added.

In case of `Overflow::Scroll` i think `egui_taffy` in the future could automatically add child layout inside egui scroll area if it overflows. I am planning to add such functionality to this crate, but it is not implemented yet.

---

Meanwhile I am welcome to PR or you can try using existing workaround functionality:

https://docs.rs/egui_taffy/latest/egui_taffy/trait.TuiBuilderLogic.html#method.add_scroll_area

This methods supports adding child `egui::Ui` directly inside egui scroll area. 
Or you can add `tui.ui(|ui| { 
    // Create scroll area manually.
})`

Then inside scroll area new egui_taffy layout can be created.

**Comment by boxofrox** [comment]
Weird that my search for *scroll* on docs.rs failed to list `add_scroll_area`.  I put my flex column into the `add_scroll_area` and I now have a scrolling flex column.  Still need to fiddle with some styles to get the column to stretch properly in the row, but that's another matter.

Thanks!

**Comment by PPakalns** [comment]
Will keep this issue open for others to find relevant information and until egui_taffy can support adding scroll area automatically based on calculated layout and taffy styles.

**Comment by PPakalns** [comment]
Added support for css overflow settings. Added commit to main branch: 2a5df5d046e6b096177332f93e6084d2249ae715

**See "Scroll demo".**  If you set `taffy::Style{ overflow: Scroll, ..default() }`, egui_taffy will automatically correctly insert egui ScrollArea with scrollbars enabled in correct axis.  

Feature available for testing, will release new egui_taffy version when I will have tested it myself in a real use case.

**Comment by PPakalns** [comment]
Released version 0.5

See README and demo for overflow example!

**Comment by boxofrox** [comment]
Works very well.  For the life of me, I could not get the `egui::ScrollArea` to fill the vertical space of a taffy row.  Thanks for this update.
